# Do not store secrets and keys in this globally accessible file.
# For your own properties, use the myconfig.properties or myconfig.yaml in the project root.
spring:
  application:
    name: "chattyCatty"
  ai:
    openai:
      chat:
      options:
        model: "gpt-3.5-turbo"
        temperature: "0.7"
      api-key: YOUR_OPEN_API_KEY_HERE
  config:
    import:
      - optional:file:./myconfig.properties
      - optional:file:./myconfig.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
  security:
    user:
      name: admin
      password: admin
  web:
    cors:
      allowed-origins: "http://localhost:3000, http://localhost:8080"
      allowed-methods: "GET,PUT,POST,DELETE"
      allowed-headers: "*"
      allow-credentials: "true"
