# Do not store secrets and keys in this globally accessible file.
# For your own properties, use the myconfig.properties or myconfig.yaml in the project root.
spring:
  application:
    name: "chattyCatty"
  ai:
    openai:
      chat:
      options:
        model: "gpt-3.5-turbo"
        temperature: "0.7"
  config:
    import:
      - optional:file:./myconfig.properties
      - optional:file:./myconfig.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
